<?php

/*
 * This file is part of the Incipio package.
 *
 * (c) Florian Lefevre
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace mgate\PersonneBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProspectRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProspectRepository extends EntityRepository
{
    public function ajaxSearch($nom)
    {
        $qb = $this->_em->createQueryBuilder();
        $query = $qb->select('n')->from('mgatePersonneBundle:Prospect', 'n')
          ->where($qb->expr()->like('n.nom', $qb->expr()->literal('%'.$nom.'%')))
          ->getQuery();

        return $query->getResult();
    }
}
