<?php

/*
 * This file is part of the Incipio package.
 *
 * (c) Florian Lefevre
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mgate\PersonneBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProspectRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProspectRepository extends EntityRepository
{
    public function ajaxSearch($nom)
    {
        $qb = $this->_em->createQueryBuilder();
        $query = $qb->select('n')->from('MgatePersonneBundle:Prospect', 'n')
          ->where($qb->expr()->like('n.nom', $qb->expr()->literal('%'.$nom.'%')))
          ->getQuery();

        return $query->getResult();
    }

    /**
     * Remplace le findAll avec une jointure sur les employés, utile notamment lors du comptage de ces derniers.
     *
     * @return array
     */
    public function getAllProspect()
    {
        $qb = $this->_em->createQueryBuilder();
        $query = $qb->select('p')
                    ->from('MgatePersonneBundle:Prospect', 'p')
                    ->leftJoin('p.employes', 'employes')
                    ->addSelect('employes')
                    ->getQuery();

        return $query->getResult();
    }

    /**
     * @param $search string a pattern we'd like to search in prospects' name
     * @param int $limit the number of prospect that research should return
     * @return array
     */
    public function searchByNom($search,$limit = 10){
        $qb = $this->_em->createQueryBuilder();
        $qb->select('p')
            ->from('MgatePersonneBundle:Prospect', 'p')
            ->where('p.nom LIKE :nom')
            ->setParameter('nom', '%'.$search.'%')
            ->setMaxResults($limit);
        $query = $qb->getQuery();
        return $query->getResult();
    }
}
