#!/bin/bash

##
# Detect the ownership of the webroot
# and run apache as that user.
#
main() {
    # Docker for Mac requires a special handling, see https://docs.docker.com/docker-for-mac/osxfs/#/ownership
    if [[ -n $(mount -t fuse.osxfs | grep /app) ]]; then
        chown -R www-data:www-data /app 2> /dev/null
        exec /usr/sbin/apache2ctl "$@"
        return
    fi

    owner="www-data"
    group="www-data"

    chown -R "$owner:$group" /var/{lock,log,run}/apache*
    chown -R "$owner:$group" var
    exec /usr/sbin/apache2ctl "$@"
}

##
# Generate a random sixteen-character
# string of alphabetical characters
randname() {
    local -x LC_ALL=C
    tr -dc '[:lower:]' < /dev/urandom |
        dd count=1 bs=16 2>/dev/null
}

main "$@"
