---
- name:     Configure vagrant user shell prompt
  template: src=bashrc.j2 dest=/home/vagrant/.bashrc

- name: Install Vim
  sudo: yes
  apt:  pkg=vim state=present

- name:     Configure Vim for vagrant user
  template: src=vimrc.j2 dest=/home/vagrant/.vimrc

- name:  Download Symfony2 auto-complete script
  shell: >
    git clone https://github.com/KnpLabs/symfony2-autocomplete.git
    && cp symfony2-autocomplete/symfony2-autocomplete.bash .symfony2-autocomplete.bash
    && rm -rf symfony2-autocomplete
  ignore_errors: true

- name: Download Git auto-complete script
  shell: curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash -o .git-completion.bash

- name:  Correct user permissions
  sudo:  yes
  shell: chown -R vagrant:vagrant /home/vagrant
