<?php

/*
 * This file is part of the Incipio package.
 *
 * (c) Florian Lefevre
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Mgate\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getNotPersonne($personne)
    {
        $qb = $this->_em->createQueryBuilder();
        $query = $qb->select('u')->from('MgateUserBundle:User', 'u')
          ->leftJoin('u.personne', 'p')
          //->addSelect('m')
          ->where('u.personne IS NULL')
          ->andWhere('p.membre IS NOT NULL');

        if ($personne) {
            $query->orWhere('u.personne = :personne')
            ->setParameter('personne', $personne);
        }

        return $query;
    }
}
